###
@baseUrl = http://localhost
@port = 6000
GET {{baseUrl}}:{{port}}/home HTTP/1.1
###
GET {{baseUrl}}:{{port}}/json HTTP/1.1
###
POST {{baseUrl}}:{{port}}/get-request-body HTTP/1.1
Content-Type: application/json

{
  "name": "Carlos",
  "username": "sprintwithcarlos",
  "email": "sprintwithcarlos@pm.me"
}

###
POST {{baseUrl}}:{{port}}/get-auth HTTP/1.1
Content-Type: application/json
Authorization: Bearer 0000

{

}